apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofood
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gofood
  template:
    metadata:
      labels:
        app: gofood
    spec:
      containers:
        - name: gofood-app
          image: fabianogoes/fiap-challenge:2.0
          ports:
            - containerPort: 8080
              # hostPort: 8080
              # protocol: TCP
          envFrom:
            - secretRef:
                name: app-secret
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD                  
      restartPolicy: Always
