apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres-secret
type: Opaque
data:
  POSTGRES_DB: Z29mb29k
  POSTGRES_USER: dXNy
  POSTGRES_PASSWORD: cHdk
  POSTGRES_HOST_AUTH_METHOD: dHJ1c3Q=
