apiVersion: v1
kind: Service
metadata:
  name: restaurant-api
  labels:
    app: restaurant-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: restaurant-api
